export const games = [
  {
    id: 1,
    price: 1749,
    title: "Devil May Cry 5",
    genre: "Action",
    img: "/images/img1.jpg",
  },
  {
    id: 2,
    price: 2339,
    title: "RESIDENT EVIL 3",
    genre: "Action",
    img: "/images/img2.jpg",
  },
  {
    id: 3,
    price: 3299,
    title: "God of War",
    genre: "Action",
    img: "/images/img3.jpg",
  },
  {
    id: 4,
    price: 1299,
    title: "Warframe",
    genre: "Action",
    img: "/images/img4.jpg",
  },
  {
    id: 5,
    price: 1960,
    title: "Metal Gear Rising",
    genre: "Action",
    img: "/images/img5.jpg",
  },
  {
    id: 6,
    price: 2999,
    title: "Far Cry 5",
    genre: "Adventure",
    img: "/images/img6.jpg",
  },
  {
    id: 7,
    price: 2999,
    title: "Assassin's Creed Valhalla",
    genre: "Adventure",
    img: "/images/img7.jpg",
  },
  {
    id: 8,
    price: 3999,
    title: "Hogwarts Legacy",
    genre: "Adventure",
    img: "/images/img8.jpg",
  },
  {
    id: 9,
    price: 1499,
    title: "Need for Speed™ Payback",
    genre: "Racing",
    img: "/images/img9.jpg",
  },
  {
    id: 10,
    price: 1499,
    title: "MotoGP™23",
    genre: "Racing",
    img: "/images/img10.jpg",
  },
  {
    id: 11,
    price: 4799,
    title: "FINAL FANTASY VII REMAKE INTERGRADE",
    genre: "RPG",
    img: "/images/img11.jpg",
  },
  {
    id: 12,
    price: 3599,
    title: "ELDEN RING",
    genre: "RPG",
    img: "/images/img12.jpg",
  },
  {
    id: 13,
    price: 989,
    title: "Divinity: Original Sin 2",
    genre: "RPG",
    img: "/images/img13.jpg",
  },
  {
    id: 14,
    price: 2000,
    title: "Crusader Kings III",
    genre: "Strategy",
    img: "/images/img14.jpg",
  },
  {
    id: 15,
    price: 2499,
    title: "Sid Meier's Civilization VI",
    genre: "Strategy",
    img: "/images/img15.jpg",
  },
  {
    id: 16,
    price: 699,
    title: "ENDLESS™ Legend",
    genre: "Strategy",
    img: "/images/img16.jpg",
  },
  {
    id: 17,
    price: 920,
    title: "Euro Truck Simulator 2",
    genre: "Simulation",
    img: "/images/img17.jpg",
  },
  {
    id: 18,
    price: 2699,
    title: "Cities: Skylines II",
    genre: "Simulation",
    img: "/images/img18.jpg",
  },
  {
    id: 19,
    price: 899,
    title: "The Sims™ 4",
    genre: "Simulation",
    img: "/images/img19.jpg",
  },
  {
    id: 20,
    price: 2999,
    title: "Cricket 24",
    genre: "Sports",
    img: "/images/img20.jpg",
  },
  {
    id: 21,
    price: 3499,
    title: "EA SPORT FC™ 24",
    genre: "Sports",
    img: "/images/img21.jpg",
  },
  {
    id: 22,
    price: 1499,
    title: "Grand Theft Auto V",
    genre: "Open World",
    img: "/images/img22.jpg",
  },
  {
    id: 23,
    price: 999,
    title: "The Witcher 3: Wild Hunt",
    genre: "Open World",
    img: "/images/img23.jpg",
  },
];
